name: Deploy Frontend to AWS S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::008971644409:role/github-actions-resume-webpage-deploy
          aws-region: us-west-1

      - name: Sync Files to S3
        run: |
          aws s3 sync . s3://anthony-resume-008971644409-us-west-1-an \
          --delete \
          --exclude ".git/*" \
          --exclude ".github/*" 